# Generated by Django 5.2 on 2025-05-10 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CountryWebsite",
            fields=[
                ("WebId", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
                ("Title", models.CharField(max_length=255)),
                ("Slug", models.SlugField(max_length=255, unique=True)),
                (
                    "MetaDescription",
                    models.CharField(blank=True, max_length=160, null=True),
                ),
                (
                    "MetaKeywords",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("UploadedAt", models.DateTimeField(auto_now_add=True)),
                ("WebsiteUrl", models.URLField(help_text="Council website url")),
            ],
        ),
        migrations.CreateModel(
            name="BusinessOpportunities",
            fields=[
                (
                    "businessopportunities_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("icon", models.CharField(max_length=50)),
                (
                    "web_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="countrywebsite.countrywebsite",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BusinessAndMedia",
            fields=[
                (
                    "businessandmedia_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("client_name", models.CharField(max_length=100)),
                ("feedback", models.TextField()),
                ("rating", models.IntegerField()),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                (
                    "web_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="countrywebsite.countrywebsite",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AboutCountry",
            fields=[
                (
                    "aboutcountry_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="about/")),
                (
                    "web_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="countrywebsite.countrywebsite",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HomePageContent",
            fields=[
                ("homepage_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "HomepageTitle",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("HomeSlug", models.SlugField(unique=True)),
                ("MetaDescription", models.TextField(blank=True, null=True)),
                (
                    "MetaKeyword",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "HomeBannerImg",
                    models.ImageField(blank=True, null=True, upload_to="home_banners/"),
                ),
                (
                    "HomeImgBannerFileName",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "HomeBannerImgAltTag",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "LogoImg",
                    models.ImageField(blank=True, null=True, upload_to="logo_images/"),
                ),
                (
                    "LogoImgFileName",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "LogoImgAltTag",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("AboutTitle", models.CharField(max_length=255)),
                ("AboutDescription", models.TextField(blank=True, null=True)),
                (
                    "AboutImg",
                    models.ImageField(blank=True, null=True, upload_to="about_images/"),
                ),
                (
                    "AboutImgFileName",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "AboutImgAltTag",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("ObjectiveTitle", models.CharField(max_length=255)),
                ("ObjectiveDescription", models.TextField(blank=True, null=True)),
                ("GalleryVideoTitle", models.CharField(max_length=255)),
                (
                    "GalleryImg",
                    models.ImageField(
                        blank=True, null=True, upload_to="gallery_images/"
                    ),
                ),
                ("GalleryVideoURL", models.URLField(blank=True, null=True)),
                (
                    "GalleryImgFileName",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "GalleryImgAltTag",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("CountryGlancesTitle", models.CharField(max_length=255)),
                ("OfficialNameTitle", models.CharField(max_length=255)),
                ("OfficialNameParagraph", models.TextField(blank=True, null=True)),
                ("CapitalCityTitle", models.CharField(max_length=255)),
                ("CapitalCityParagraph", models.TextField(blank=True, null=True)),
                ("LocationTitle", models.CharField(max_length=255)),
                ("LocationParagraph", models.TextField(blank=True, null=True)),
                ("AreaTitle", models.CharField(max_length=255)),
                ("AreaParagraph", models.TextField(blank=True, null=True)),
                ("PopulationTitle", models.CharField(max_length=255)),
                ("PopulationParagraph", models.TextField(blank=True, null=True)),
                ("LanguageTitle", models.CharField(max_length=255)),
                ("LanguageParagraph", models.TextField(blank=True, null=True)),
                ("ExportsTitle", models.CharField(max_length=255)),
                ("ExportsParagraph", models.TextField(blank=True, null=True)),
                ("ImportTitle", models.CharField(max_length=255)),
                ("ImportParagraph", models.TextField(blank=True, null=True)),
                ("CurrencyTitle", models.CharField(max_length=255)),
                ("CurrencyParagraph", models.TextField(blank=True, null=True)),
                ("CountryCodeTitle", models.CharField(max_length=255)),
                ("CountryCodeParagraph", models.TextField(blank=True, null=True)),
                ("TimeZoneTitle", models.CharField(max_length=255)),
                ("TimeZoneParagraph", models.TextField(blank=True, null=True)),
                (
                    "web_id",
                    models.ForeignKey(
                        db_column="web_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="countrywebsite.countrywebsite",
                    ),
                ),
            ],
        ),
    ]
